Streamlink 5.5.0 and Python 3.8 are required
AttributeError: module 'urllib3.util.url' has no attribute 'PERCENT_RE' · Issue #5324 · streamlink/streamlink
  https://github.com/streamlink/streamlink/issues/5324

PEP 537 – Python 3.7 Release Schedule | peps.python.org
  https://peps.python.org/pep-0537/#lifespan