Be compatible with Streamlink 6.0.0 (#17)
* docs: Streamlink versions of 4.3.0+ are required due to eplus.py

Sorry, I've already broken the compatibility since 57ea5df855fdea4042fb93d1bcec8d9f874a5e78 . 

AttributeError: module 'streamlink.plugin.api.validate' has no attribute 'none_or_all'

https://github.com/streamlink/streamlink/commit/cb56e063c96250f5f8090b2c298872c10edbc725

* fix: drop "Plugin.__init__(self, url) compatibility wrapper"

https://streamlink.github.io/deprecations.html#plugin-init-self-url-compatibility-wrapper