eplus: gracefully shutdown when live ends (rewrite) (#12)
* eplus: gracefully shutdown when live ends

Since the playlist of an ended Eplus live streaming doesn't contain an
  "#EXT-X-ENDLIST" tag, Streamlink will try to reload it continuously
  and finally exit with errors due to timeout:

    [stream.hls][debug] Reloading playlist
    [stream.hls][debug] Reloading playlist
    ...
    [stream.hls][debug] Reloading playlist
    error: Error when reading from stream: Read timeout, exiting

Thus we think:
  If the playlist remains unchanged for a while, the live has ended.

Original author: ipid <ipid@users.noreply.github.com>

Co-authored-by: ipid <ipid@users.noreply.github.com>
Co-authored-by: Mozi <29089388+pzhlkj6612@users.noreply.github.com>

* eplus: remove too detailed logs

Don't be so verbose.

Co-authored-by: Peter Rowlands (변기호) <peter@pmrowla.com>

Co-authored-by: ipid <ipid@users.noreply.github.com>
Co-authored-by: Peter Rowlands (변기호) <peter@pmrowla.com>