eplus: support account; refresh cookies within 15 mins; check "drm_mode" (#23)
* eplus: support account; refresh session within 15 mins; check "drm_mode"

"drm_mode" lives forever, while "drmEncryptKey" does not.

* eplus: code style

* eplus: pass extra params to EplusHLSStream via kwargs

* eplus: don't pass extra params to EplusHLSStream via kwargs

This partially reverts commit a8d50d26779756114364317fc2bb89938a620e63.

This is a Streamlink 6 feature (https://github.com/streamlink/streamlink/commit/d59377398e833ad8c4deb7a6ed85e062e616a5fd). Don't be too radical.

* eplus: terminology! we are updating the session by refrshing cookies

* eplus: re-login account if required when refreshing cookies

* eplus: detect if cookies are invalidated; type annotations; clean code

* eplus: use "m3u8_urls" instead of "channel_urls"; clean code

If no stream_session, everything is dead.

* eplus: check if m3u8 url list is be parsed

* eplus: set up session updater during preparing streams

* eplus: allow empty m3u8 url list or empty stream session url

The Eplus DRM test page has neither list_channels nor the stream session.

* eplus: import streamlink.session.http.HTTPSession

* eplus: compatibility for Python<=3.10 and Streamlink<6.6.0

- https://peps.python.org/pep-0604/
- https://streamlink.github.io/deprecations.html#httpsession-and-httpadapters

* Streamlink 5.5.0 and Python 3.8 are required

AttributeError: module 'urllib3.util.url' has no attribute 'PERCENT_RE' · Issue #5324 · streamlink/streamlink
  https://github.com/streamlink/streamlink/issues/5324

PEP 537 – Python 3.7 Release Schedule | peps.python.org
  https://peps.python.org/pep-0537/#lifespan

* eplus: hide the password in logs

* eplus: hide the email or the phone number in logs

Privacy No.1